// worker-configuration.d.ts is regenerated by `wrangler types` from wrangler.jsonc's bindings,
// which doesn't cover secrets (never written to that checked-in file). Declaration-merge the
// secret onto both the global `Env` interface (used throughout worker/src) and `Cloudflare.Env`
// (what `cloudflare:workers`' exported `env` and the Agents SDK's `Agent<Env = Cloudflare.Env>`
// default resolve to) — worker-configuration.d.ts declares both, kept structurally identical, so
// augmenting only one would make them diverge and break assignability between them.
interface Env {
  ANTHROPIC_API_KEY: string
}
declare namespace Cloudflare {
  interface Env {
    ANTHROPIC_API_KEY: string
  }
}
